### PR TITLE
Replace SNAP graph with our own implementation

### PR DESCRIPTION
**Pull request by ghost**
I have finally finished the migration to our own graph library. The new version passed all my own tests locally, but I only use DNL (single class and biclass). So I would appreciate some testing work for other use cases.

There are still some left to be done:

- ~The Python binding for multimodal DTA is broken. I have committed the broken version (32192eaa0a032b5a28c1b2cf56f3b12f610750b3), and I would appreciate any help on that.~ *Fixed in 7f8cf8b3087a97dbae7aa4f3012a6f1948ea1eb0.*
- ~Workzone functionality is broken. We need to add support for deleting links from a graph for that.~ ***This is a bit tedious, and I think workzone is not commonly used? So I do not think this is a blocker.***
- ~Cleanup to remove duplicated snippets, and a review on memory management.~ *Done.*

### CODE REVIEW

**Comment by psychogeekir** [comment]
Thanks, I will check on the multimodal DTA binding.

**Review by psychogeekir — COMMENTED** [review]
I got the same compilation error. 

error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = macposts::graph::Graph<TInt, TInt, macposts::Empty, macposts::Empty, true>::Link; _Dp = std::default_delete<macposts::graph::Graph<TInt, TInt, macposts::Empty, macposts::Empty, true>::Link>]’

It seems due to attempting to copy or clone a 'std::unique_ptr'. But I have yet to identify where the cause is.

**Comment by ghost** [comment]
It was my oversight. Should be fixed now.

**Comment by ghost** [comment]
I do not think workzone is commonly used (and I am not even sure if it really worked before). So I do not think workzone issue is a blocker for this PR.

I have fixed the other two TODOs, and this is ready for review. Please let me know if you find any problems.

Besides, I suggest making a new release before merging (Maybe 0.4.2? Be sure to update the change log.). I am planning to completely drop SNAP in the next big release.

**Comment by psychogeekir** [comment]
Thanks! I will check it out.On Mar 15, 2024, at 15:30, kunhtkun ***@***.***> wrote:﻿
I do not think workzone is commonly used (and I am not even sure if it really worked before). So I do not think workzone issue is a blocker for this PR.
I have fixed the other two TODOs, and this is ready for review. Please let me know if you find any problems.
Besides, I suggest making a new release before merging (Maybe 0.4.2? Be sure to update the change log.). I am planning to completely drop SNAP in the next big release.

**Comment by psychogeekir** [comment]
I released v0.4.2 and am about to merge this into dev.

When releasing v0.4.2, I got this warning

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-python@v4, actions/upload-artifact@v3

Perhaps we can change v3 to v4 in release.yml?

**Pull request merged**
