### PR TITLE
modify install_cc to intall cc for all links

### PR DESCRIPTION
**Pull request by psychogeekir**
Since column generation and function build_link_cost_map() in DUE, DSO, and DODE require all link's travel time, I modify install_cc to be compatible with my testing cases.

### CODE REVIEW

**Comment by ghost** [comment]
Should we remove `register_links` then?

**Comment by ghost** [comment]
Also, should we do this for `install_cc_tree` as well?

**Comment by psychogeekir** [comment]
I think we can leave register_link() as is since we don’t need cc_tree for each link in those procedures and installing cc_tree for each link will consume too much memory.On Jun 6, 2023, at 15:59, kunhtkun ***@***.***> wrote:﻿
Also, should we do this for install_cc_tree as well?

**Comment by ghost** [comment]
Then I honestly do not like this inconsistency, but I do not have a strong feeling either. I will leave it to your decision.

**Pull request merged**
