### PR TITLE
Delivery traffic

### PR DESCRIPTION
**Pull request by psychogeekir**
Add code about modeling normal and delivery traffic. The delivery vehicles can have multiple pickup and dropoff locations, i.e., O1, D1, O2, D2, .... Right now it is for DNL and does not have Python APIs.

### CODE REVIEW

**Comment by ghost** [comment]
Let us bump the version first? I think this is a big change that warrants a new development cycle.

We are currently in 0.3.1, and I think this should go into 0.3.2 at least.

**Comment by psychogeekir** [comment]
Agreed. Let us do that.

**Comment by psychogeekir** [comment]
@kunhtkun How do we do that? Do you mean we merge `dev` into `main` first and tag it as v0.3.1 and release this version? I kind of remembered that you mentioned to me last time there is something I should know about tagging and releasing but I cannot recall. Can you remind me of that? Thanks.

**Comment by ghost** [comment]
I am not sure if we need more testing. If you think the current
changes are ready to be landed on main, we could merge dev to main and
tag a new release. I have a few things in mind but I do not have time
for them now. So I will follow your decision.

If you are not familiar with Git tags, we may need to work together on it.

**Pull request merged**
