### PR TITLE
Update version number to v0.3.1 in some files

### PR DESCRIPTION
**Pull request by psychogeekir**

### CODE REVIEW

**Comment by psychogeekir** [comment]
I am not familiar with tagging and releasing, sorry about the back and forth.

**Comment by ghost** [comment]
I saw you pushed a tag and then deleted it, which should be generally avoided.

Also, it seems that you made a release manually on GitHub, which is not necessary because a bot will do that for tags start with "v".

**Comment by psychogeekir** [comment]
Thanks for the tip. Do you mean I can just tag it and then GitHub will automatically release it?

**Comment by ghost** [comment]
Yes. See '.github/workflows/release.yml'.

The general steps for making a release are:

- Create a version bump commit (e.g., 43d18bc60089f0c3e46db5036ae27c0593e2a554).
- Tag the commit with a "vN.N.N" tag.
- Push the tag.

For tags, please check `man git-tag(1)'. The command is something like:

    git tag -a -m 'macposts v0.3.1' 'v0.3.1' COMMIT

(Replace COMMIT with the desired one, or omit it to use the current HEAD.)

Before you push the tag, please check if it looks good. It is advised
to not delete a published tag.

**Comment by psychogeekir** [comment]
OK, thanks.

**Comment by psychogeekir** [comment]
Can you please approve this pull request so we can release it? Thanks.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Sorry I thought I had approved it. Now done.

**Comment by ghost** [comment]
By the way, I actually would like to update the notebook file only when necessary, e.g., when we change the API and the notebook does not run (which will be checked by pytest).

I myself am not a fan of Jupyter notebooks because they are not very friendly to Git (or VCS in general). If you need to bump the version tag used on Colab (which could be removed all together once #17 is resolved), you may update that number only without rerunning the whole thing. Our testing does not compare plots anyway.

**Pull request merged**
