### PR TITLE
Tighten ignore patterns

### PR DESCRIPTION
**Pull request by ghost**
This is a followup to commit 56a0e78430c251de7b3b33bbf7329be4a1139d6c. The original version should probably work, but I think it is better to be more specific.

Changes:
* .gitignore: Ignore only directories directly under the project root.

### CODE REVIEW

**Comment by ghost** [comment]
By the way, as we are now mainly doing our work on `dev`, do you think we should run tests for the `dev` branch as well?

**Comment by psychogeekir** [comment]
> By the way, as we are now mainly doing our work on `dev`, do you think we should run tests for the `dev` branch as well?

I think that will be great.

**Review by psychogeekir — APPROVED** [review]

**Comment by psychogeekir** [comment]
Hi, Pengji @kunhtkun, just seeking a piece of advice from you about managing this repo. I enabled some protection rules on `main`, which forbid direct push to this branch. Do you think it is good to enable "requires linear history" as well? But this will forbid "merge commits" and only allow "squash and merge" and "rebase and merge".

**Comment by ghost** [comment]
I think it is already enabled? I cannot use "merge commits" now.

Anyway, I myself prefer linear history for PRs because of the clean Git history. So I would recommend enabling it.

**Comment by psychogeekir** [comment]
Yes, I enabled that. Then since you mentioned you preferred not to squash the commits either, probably we stick to “rebase and merge” option.

**Comment by ghost** [comment]
To clarify, I am fine with squash. Some like to commit frequently when making PRs, and it is better IMO to merge those closely related, small commits as one commit -- which is "squash and merge".

I generally do not do that, so I said to use rebase for my PRs.

**Pull request merged**
